apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: {{ .Values.namespace.orderernamepsace }}

spec:
  loadBalancerIP: {{ .Values.ingress.addr }}
  externalIPs:
  - {{ .Values.ingress.addr }}
  ports:
  - name: "ordererrequest"
    port: 7050
    protocol: TCP
    targetPort: 7050
  selector:
    service: {{ .Release.Name }}-orderer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-orderer
  name: {{ .Release.Name }}-orderer
  namespace: {{ .Values.namespace.orderernamepsace }}
spec:
  replicas: {{ .Values.fabricOrderer.replicas }}
  selector:
    matchLabels:
      service: {{ .Release.Name }}-orderer
  template:
    metadata:
      name: {{ .Release.Name }}-orderer
      labels:
        service: {{ .Release.Name }}-orderer
      namespace: {{ .Values.namespace.orderernamepsace }}
    spec:
      hostAliases:
      - ip: "{{ .Values.fabricOrderer.addr }}"
      hostnames:
       - "orderer.{{ .Values.fabricOrderer.orgDomain }}"
      containers:
      - command:
        - orderer
        env:
        - name: GODEBUG
          value: netdns=go+1
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: CORE_VM_ENDPOINT
          value: unix:///var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: corporate-hyperledger-cluster_poc
        - name: GRPC_TRACE
          value: "all=true"
        - name: GRPC_VERBOSITY
          value: debug
        - name: CORE_PEER_NETWORKID
          value: corporate-hyperledger-cluster_poc
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: "0.0.0.0"
        - name: ORDERER_GENERAL_LISTENPORT
          value: "30724"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value:  /etc/crypto-config/opensource.com/HLF/channel-artifacts/orderer-genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: {{ .Values.fabricOrderer.msp }}
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /etc/crypto-config/opensource.com/HLF/crypto-config/ordererOrganizations/{{ .Values.fabricOrderer.orgDomain }}/orderers/orderer.{{ .Values.fabricOrderer.orgDomain }}/msp
        {{  if eq .Values.fabricOrderer.consensusType "kafka" }}
        - name: ORDERER_KAFKA_VERBOSE
          value: "true"
        {{- end }}
        image: {{ .Values.fabricOrderer.image }}:{{ .Values.fabricOrderer.tag }}
        name: {{ .Release.Name }}-orderer
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        ports:
        - containerPort: 7050
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: {{ .Release.Name }}-docker-sock
          - mountPath: /etc/crypto-config
            name: {{ .Release.Name }}-crypto-config
            readOnly: true
          - mountPath: /var/hyperledger/production
            name: orderer-datadir
      volumes:
      - name: {{ .Release.Name }}-docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: orderer-datadir
      - name: {{ .Release.Name }}-crypto-config
{{ toYaml .Values.cryptoConfigMount | indent 8 }}
        
  volumeClaimTemplates:
  - metadata:
      name: orderer-datadir
      namespace: {{ .Values.namespace.orderernamepsace }}
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
          memory: 1Gi
