apiVersion: v1
kind: Service
metadata:
  name: ca2
  namespace: {{ .Values.namespace.org2namespace }}
spec:
  loadBalancerIP: {{ .Values.ingress.addr }}
  externalIPs:
  - {{ .Values.ingress.addr }}
  ports:
  - name: "api"
    port: 7054
    protocol: TCP
    targetPort: 7054
  selector:
    service: {{ .Release.Name }}-ca2
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-ca2
  name: {{ .Release.Name }}-ca2
  namespace: {{ .Values.namespace.org2namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-ca2
  template:
    metadata:
      name: {{ .Release.Name }}-ca2
      labels:
        service: {{ .Release.Name }}-ca2
      namespace: {{ .Values.namespace.org2namespace }}
    spec:
      hostAliases:
      - ip: "{{ .Values.fabricOrderer.addr }}"
      hostnames:
       - "orderer.{{ .Values.fabricOrderer.orgDomain }}"
      containers:
      - command:
        - fabric-ca-server
        - start
        - --ca.certfile
        - /etc/crypto-config/opensource.com/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg2.domain }}/ca/ca.{{ .Values.fabricOrg2.domain }}-cert.pem
        - --ca.keyfile
        - /etc/crypto-config/opensource.com/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg2.domain }}/ca/{{ .Values.fabricCa2.keyStoreHash }}_sk
        - -b
        - admin:adminpw
        - -d
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca2.{{ .Values.fabricOrg2.domain }}
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        image: {{ .Values.fabricCa2.image }}:{{ .Values.fabricCa2.tag }}
        name: {{ .Release.Name }}-ca2
        ports:
        - containerPort: 7054
        volumeMounts:
        - mountPath: /etc/crypto-config
          name: {{ .Release.Name }}-crypto-config
          readOnly: true
      volumes:
      - name: {{ .Release.Name }}-crypto-config
{{ toYaml .Values.cryptoConfigMount | indent 8 }}
