apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-peer0Org2
  name: {{ .Release.Name }}-peer0Org2
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-peer0Org2
  template:
    metadata:
      name: {{ .Release.Name }}-peer0Org2
      labels:
        service: {{ .Release.Name }}-peer0Org2
      namespace: {{ .Values.namespace }}
    spec:
      # hostAliases:
      # - ip: "{{ .Values.fabricOrderer.addr }}"
      # hostnames:
      #  - "orderer.{{ .Values.fabricOrderer.orgDomain }}"
      containers:
      - command:
        - peer
        - node
        - start
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ID
          value: peer0Org2.{{ .Values.fabricOrg2.domain }}
        - name: CORE_PEER_ADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: 0.0.0.0:7051
        - name: CORE_PEER_EXTERNALENDPOINT
          value: "true"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/crypto-config/opensource.com/HLF/crypto-config/peerOrganizations/{{ .Values.fabricOrg2.domain }}/peers/peer0.{{ .Values.fabricOrg2.domain }}/msp
        - name: CORE_PEER_LOCALMSPID
          value: {{ .Values.fabricOrg2.msp }}
        image: {{ .Values.fabricPeer.image }}:{{ .Values.fabricPeer.tag }}
        name: {{ .Release.Name }}-peer0Org2
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        ports:
        - containerPort: 7051
        - containerPort: 7053
        - containerPort: 7052
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: {{ .Release.Name }}-docker-sock
        - mountPath: /etc/crypto-config
          name: {{ .Release.Name }}-crypto-config
          readOnly: true
        - mountPath: /var/hyperledger/production
          name: {{ .Release.Name }}-fabric
      volumes:
      - name: {{ .Release.Name }}-docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: {{ .Release.Name }}-fabric
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-peer0Org2-pvc
      - name: {{ .Release.Name }}-crypto-config
{{ toYaml .Values.cryptoConfigMount | indent 8 }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-peer0Org2-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-peer0Org2-pvc
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi