
name: "supplyChain"

x-type: "hlfv1"


description: "SupplyChain"

version: "1.0"


channels:

  mychannel:
    orderers:
      - orderer.example.com

    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - supplychain:v2

organizations:
  org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - test-ca1
    adminPrivateKey:
      path: artifacts/data/orgs/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/3e43eb0a2e47b1ed718c138da1041096aec88c058fc0f03b68f2d1775d3abc33_sk
    signedCert:
      path: artifacts/data/orgs/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpc://10.63.249.66:7050

    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15
      grpc.http2.keepalive_time: 60000

    tlsCACerts:
      path: artifacts/data/orgs/ordererOrganizations/example.com/ca/ca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpc://10.63.241.223:7051
    eventUrl: grpc://10.63.241.223:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.http2.keepalive_time: 60000
    tlsCACerts:
      path: artifacts/data/orgs/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem

  peer0.org2.example.com:
    url: grpc://10.63.245.74:7051
    eventUrl: grpc://10.63.245.74:7053
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.http2.keepalive_time: 60000
    tlsCACerts:
      path: artifacts/data/orgs/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem


certificateAuthorities:
  test-ca1:
    url: http://104.198.229.69:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: artifacts/data/orgs/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: test-ca1

